### ISSUE TITLE
Inconsistency when resolving libs with relative symbolic links

### ISSUE THREAD

**Issue by CristianDG** [DanielGavin/ols#325] opened 2024-03-23 18:41 UTC
![image](https://github.com/DanielGavin/ols/assets/39601699/5d17f5d9-ff66-4287-a8e7-8f533c6284a0)
![image](https://github.com/DanielGavin/ols/assets/39601699/b3e0cc3a-36b3-4e51-9eda-a5710f1027c6)
![image](https://github.com/DanielGavin/ols/assets/39601699/46b47268-e0ac-4721-ab43-a3c4f38a68c4)
![image](https://github.com/DanielGavin/ols/assets/39601699/b19e2c91-b241-4e14-bdd8-0121e62b24f1)
odin version: `dev-2024-03:4c35633e0`
ols.json:
```json
{
  "collections": [
    {"name": "shared", "path": "shared"}
  ]
}
```

**Comment by DanielGavin** [comment] 2024-03-23 20:22
Does it work with Odin compiler? Don't think there is any os features in the `odin` core to support symlinks, so this won't be supported until then.

**Comment by CristianDG** [comment] 2024-03-23 20:55
I've created an issue [here](https://github.com/odin-lang/Odin/issues/3315) showing another side of this problem.

I was thinking that it wouldn't be necessary to create an issue here, but I don't know how ols resolves links, I believe that if the problem is resolved in the compiler it will be resolved in ols without changing anything

**Comment by DanielGavin** [comment] 2024-03-23 21:05
It won't be resolved here.  I have to implement whatever Odin decides to do. So the issue is fine here as well.

**Closed** 2024-04-13 10:06 UTC
