### ISSUE TITLE
Crash in VSCode passing proc value to function

### ISSUE THREAD

**Issue by WalterPlinge** [DanielGavin/ols#16] opened 2021-02-01 02:02 UTC
### Code snippet
```
package main

import la "core:math/linalg"
import "core:strings"

main :: proc() {
	sb := strings.make_builder_len(la.length);
}
```
### Reproduce
Typing in the name of the `length` function to the `make_builder_len` function closes the server.
I know that that shouldn't be the parameter to that function, but I was preemptively putting a length variable as the argument before the variable was declared, so it used the length function instead.

**Comment by DanielGavin** [comment] 2021-02-01 11:08
@WalterPlinge I cannot reproduce the problem.

What version of odin are you using?

**Comment by WalterPlinge** [comment] 2021-02-10 20:10
@DanielGavin sorry for the late reply. I've just checked it again and I cannot reproduce it either. I have updated odin and ols since I opened this issue so I don't know if it still exists.

**Comment by DanielGavin** [comment] 2021-02-10 20:11
@WalterPlinge I'll close it then. You can always add the same issue later if the bug still exists somewhere.

**Closed by DanielGavin** 2021-02-10 20:11 UTC
