### ISSUE TITLE
Incorrect syntax error when assigning proc to struct variable

### ISSUE THREAD

**Issue by parkerlamb** [DanielGavin/ols#317] opened 2024-03-09 13:02 UTC
ols incorrectly raises a syntax error when assigning a `proc` to a struct variable.

Example:
```odin
package test

import "core:fmt"

main :: proc() {
    MyStruct :: struct {
        do_action: proc()
    }

    my_struct := MyStruct {
        do_action = proc() {
            fmt.println("Action called!")
        }
    }

    my_struct.do_action()
}
```

ols says `expected '}' after compound literal, got 'newline'` on line 13, while running the same code with odin correctly prints `Action called!`.

ols version: `v0.1.27` (vscode)
odin version: `dev-2024-02:539cec74`

**Comment by DanielGavin** [comment] 2024-03-09 21:30
This is caused by and issue with `core:odin/parser` not being in sync with the odin compiler. It has to be fixed in Odin.

**Closed by DanielGavin** 2024-03-09 21:30 UTC
