### ISSUE TITLE
[odinfmt] weird `return {...}` struct formatting

### ISSUE THREAD

**Issue by jakubtomsu** [DanielGavin/ols#346] opened 2024-04-15 14:43 UTC
A return statement with a multiline struct initializer gets formatted weirdly.

Here is an example. This is the what it should look like:
```odin
return {
	alloc_fn = allocator_alloc_func,
	free_fn = allocator_free_func,
	user_data = cast(rawptr)context_ptr,
}
```

And here is what it gets formatted into:
```odin
return(
	 {
		alloc_fn = allocator_alloc_func,
		free_fn = allocator_free_func,
		user_data = cast(rawptr)context_ptr,
	} \
)
```

The parentheses and backslash don't look very good...

**Comment by DanielGavin** [comment] 2024-04-15 22:11
The format style was thought for: 
```
return(
	imp1.derived.(^ast.Import_Decl).fullpath <
	imp2.derived.(^ast.Import_Decl).fullpath \
)
```
Maybe that should be changed aswell, but with braces I agree it makes no sense.

**Comment by jakubtomsu** [comment] 2024-04-16 05:00
I think this looks the best:
```odin
return imp1.derived.(^ast.Import_Decl).fullpath <
       imp2.derived.(^ast.Import_Decl).fullpath \
```

The braces do make things a bit clearer, but it's not something I would write without odinfmt. I'm not entirely sure but I think the `core:` libs don't use them as well.

**Comment by Feoramund** [comment] 2024-04-21 06:23
Looks to be a duplicate of #271.

**Comment by DanielGavin** [comment] 2024-04-28 14:35
Fixed.

**Closed by DanielGavin** 2024-04-28 14:35 UTC
