### ISSUE TITLE
Wrong semantic tokens in proc type params without names

### ISSUE THREAD

**Issue by thetarnav** [DanielGavin/ols#293] opened 2024-01-14 09:31 UTC
Seems like semantic tokens don't expect a procedure to not have parameter names, but that is a valid syntax when defining a proc type.

```odin
Func :: proc (u32, int, string)
```

With semantic tokens:

![image](https://github.com/DanielGavin/ols/assets/24491503/993c4628-8d47-4bbd-9033-c942c63b5fea)

Without:

![image](https://github.com/DanielGavin/ols/assets/24491503/a3fd6fad-cb4d-4bc7-80e4-85c3b277092d)

The first letter has a token of `parameter` instead of `support.type` or `entity.name.type`.

**Comment by thetarnav** [comment] 2024-03-18 13:47
Sometimes similar thing happens to multiple unnamed return values.
This is from `odin/core/os/os_linux.odin`
![image](https://github.com/DanielGavin/ols/assets/24491503/c0b821a1-e73d-4c89-b5a9-72372e65a248)

**Comment by DanielGavin** [comment] 2024-03-18 15:29
Should be fixed. It's caused by  `core:odin/parser` apparently sets the name to be "_" when the parameters names are empty. I now handle that.

**Closed** 2024-03-20 22:27 UTC
