### ISSUE TITLE
Newline in struct initialization not handled properly, And trailing space in struct initialization causes crash

### ISSUE THREAD

**Issue by sackboy19** [DanielGavin/ols#288] opened 2023-12-27 03:17 UTC
Info: latest build, vscode plugin, odin version dev-2023-12:31b1aef4

<img width="668" alt="image" src="https://github.com/DanielGavin/ols/assets/83356017/9e59be45-56c9-4d34-828d-5cd48ff2235d">

The image shows valid compiling odin code:
```go
test :: struct {
	x: int,
	y: int,
	z: int
}

main :: proc() {
	// these don't work
	t := test {
		x = 1,
		y = 2,
		z = 3 // trailing space crashes OLS
	}
	t2 := test {
		x = 1,
		y = 2,
		z = 3 // no space but only a newline causes error even though odin compiles it fine
	}

	// these work fine:
	t3 := test {
		x = 1,
		y = 2,
		z = 3,
	}
	t4 := test {
		x = 1,
		y = 2,
		z = 3}
}
```

Having a trailing space in struct initializer causes ols to crash
Having a trailing newline in struct initializer causes ols to report an error, however it should not
Having a trailing comma or curly brace fixes it

**Comment by DanielGavin** [comment] 2023-12-27 08:56
When you say crash. Do you mean an actual crash where `vscode` mentions it crashes, or it doesn't work after.

All these errors are related to `core:odin/parser` that requires trailing commas, and cannot be fixed here.

**Comment by dannylol19** [comment] 2023-12-27 13:55
I mean crash where vscode displays the message "Odin Language Server has crashed more than 5 times"

And ok I see, so the issue is with odin's parser module

**Comment by DanielGavin** [comment] 2023-12-27 14:21
I'll try and check the crashing one. Maybe I can make it not crash, but the errors about not having a trailing comma has to be fixed in the parser package.

**Comment by DanielGavin** [comment] 2024-10-05 22:57
Fixed.

**Closed by DanielGavin** 2024-10-05 22:57 UTC
